---
- hosts: localhost
  become: yes
  tasks:    
    - ec2_vpc_igw:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "us-east-1"
        state: "present"
        tags:
          Name: "md-igw"
      register: igw_result
